apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  selector:
    app: jenkins
  type: ClusterIP
  ports:
  - name: jenkins-ui
    port: 8080
    targetPort: 8080
  - name: jenkins-jnlp
    port: 50000
    targetPort: 50000    