apiVersion: v1
kind: PersistentVolume
metadata:
  name: rancher-storage
  namespace: rancher
  labels:
    app: rancher-storage
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: nas.crazyzone.be
    path: "/volume1/docker-storage/rancher"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rancher-storage-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: rancher-storage
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem