apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: euro-office-passwords
  namespace: eurooffice
spec:
  encryptedData:
    postgres-password: AgC9Lm+VFjhoVOn3a8WAl8Ix6jvJTDlzRqNd8at5jDOZSU27gyJl+IGhd4lFih0RFZKP8NfNMkjOrKtec4KduAMVIhyxy0K8AoEON92pQ8Lnke+IabFfmmV9whNwS+db5Q1zsiEwpSei6E0jArLWzGczw5kMGxAniYU4HSOtQL4mF8dREgzKoHLBn521eHDr0CveCxduQC55piQ/HXvwrPSrwQytbq7Z7ogpvipPjVcf0ISajovKZNY5a4JmzhUjNMyN8eaTg29IfIVZSilrlR0j/0GQB8lgCIc8catSbf3sHF+8X9L2uY1Gi9YRdr2Bt1OPceVNaon8hDb0BMJYIIJGvdUBjm+oTjlUXCWW3M1ky3+k+Ji7fJd6JYI4YQmaYE8sF2e05j9ZfTLxvIuWJ6BCmKHYALLBGWIeiZYEqy70+2pfNrqfcsgzXfQC29MklaZ3A9tPMpynrZrGrwqFiZLYGBvH0vZRTdX/SUPmsivwnZvOPLzZejNKiHjUhD0XJOTh34udvBDYa8FMjHAF7f2vHDD597KW1HFUA11McFlqX6jFt2jmC/1FIHEQsTCN2kb64cID222hPpGQyYchRP1ikj+uba6HUb7m8T2HkzlWE4hrQxgunv0xVvBXPJuKpNdk1hxhKsAF1CP5LAMzQNJJBJ/qkqYG40ejx+mylk6qoD5me+4Epjs9pUxldSs3W4SgXrfIKMxAVM5D36/9/7BgNVW1ew==
    rabbitmq-password: AgCI7jM/uPxHcPPJVVieHq8AzluDINDkNv8KhtcnjoSIBNI3FsaSmymWS949ufEXgmUm7xT1WCWH4fRhGjOEJaJlwQUaDkwTmphoV/+dZc6jFA1sAWDWeLGxIW8sYb9nP6nEHiWKnY5SNe1An3imUW29yrZDxz6BLgzRu31xhJgbKsuungavmzVW2Aj7zXxdVuftYZ+iSZN966YH0xdW8u8c/A0Ny51hnTq0n57C/KdOu6wRDgTmj12bLgVBHZDuSdLcrz8p8nqvlvYFXSlRjFoHT6ml1MUS6nIextoJ6+U8m+BNJDniKLPreGPGs9E4Uxsl0WyELdi85DTWysOxMDqeOezxYQ3mrEaSdaNMYHJ+x51DZVFejxNYS8Ro0O3NEYhoziPdseH1yrH2QU9uFLCBkdL83zLgAQZ8O5dGLKr94vWK8VFxZSobTGpizBwQkHtTsOI6xNZF0Ff11Wdapw5kOQZRIA12GjG/MaQySASQhOuOKz8JSWD8/HNz5bNB43K/Cx0YjsCkSbCWly+VY0nmuM4DGAw6InG2ppdFio3VaXOjDJYjpx3vN7sV9H5LOZYiPm9mIhfkvpYb0D5m9kVqRJrhPCqpds06kBjkPCiqPi29WipUkKXiY/0iXkS2I8TPakl7n/OiIKyQllBfHiSdoYugQYZHyWixLivYRrIvFdcpEAo5y9Q2ldXHFmRl1iYdThDKsXnGhMhC/VoVBlRXCTiN46DSkryQMvCbvGjCsw==
  template:
    metadata:
      creationTimestamp: null
      name: euro-office-passwords
      namespace: eurooffice
    type: Opaque