{{- $docs := .Values.docs | default dict -}}
{{- $runtimeOverrides := $docs.runtimeOverrides | default dict -}}
{{- $configMap := $runtimeOverrides.configMap -}}
{{- $filename := $runtimeOverrides.filename -}}
{{- $settings := $runtimeOverrides.settings | default dict -}}
{{- if $configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configMap }}
data:
  {{ $filename }}: |
{{ $settings | toPrettyJson | nindent 4 }}
{{- end }}
