apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $.Values.name }}
  name: {{ $.Values.name }}
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: {{ $.Values.name }}
  type: ClusterIP