apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry-ui
  name: registry-ui
spec:
  ports:
  - name: {{ .Values.name }}
    port: 80
    targetPort: 8080
  selector:
    app: {{ .Values.name }}
  type: ClusterIP