apiVersion: v1
name: harbor
version: 1.19.2
appVersion: 1.19.2
description: Artifact repository for crazyzone
dependencies:
  - name: harbor
    version: "1.19.2"
    repository: "https://helm.goharbor.io"
