apiVersion: v1
name: kickstart
version: 0.0.4
appVersion: 0.0.4
description: web server providing kickstart files
dependencies:
  - name: kickstart
    version: "0.0.4"
    repository: "oci://harbor.crazyzone.be/crazyzone-helm"