apiVersion: v2
name: plugwise
version: 0.0.3
appVersion: 0.0.3
description: Application to communicate with the plugwise stick and circles
dependencies:
  - name: plugwise
    version: "0.0.3"
    repository: "oci://harbor.crazyzone.be/crazyzone-helm"