plugwise:
  global:
    existingRegisrySecret: registry-crazyzone-cred-plugwise
  device:
    path: /dev/ttyUSB0
  resources:
    replicaCount: 1
  hostnames:
    - plugwise.crazyzone.be
  ingress:
    enabled: true
    labels:
      trigger: "1"
    hosts: 
    - host: plugwise.crazyzone.be
      paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - plugwise.crazyzone.be
      secretName: secret-tls
