nomadesk:
  global:
    registry: "harbor.crazyzone.be/nomadesk"
    imagePullSecrets:
      - registry-nomadesk-cred
  nomadesk:
    hostname: "nmd.crazyzone.be"
    version: "dev"
    admin:
      autocreate: true
      email: "nico.vanlaerebeke@unifiedpost.com"
      enablePartnerPortal: true
    devdocs:
      enabled: true
    licenseserver:
      enabled: true
    shorturl:
      enabled: true
    storage:
      enablePersistentStorage: true
      existingVolumeClaim: nmd-storage-claim
    syncserver:
      port:
        type: Ingress
    ingress:
      enabled: true
    db: 
      autocreate: true
      postgresHost: "nmd.crazyzone.be"
      postgresPort: 30000
      postgresDbPassword: "password"
    redis:
      hostname: "nmd.crazyzone.be"
      port: 30002
      password: "password"
  postgres:
    enabled: true
    existingClaim: nmd-storage-db-claim
  redis:
    enabled: true
    master:
      persistence:
        enabled: false 
  minio:
    enabled: true
    mode: standalone
    replicas: 1
    rootUser: admin
    rootPassword: password
    resources:
      requests:
        memory: 512Mi
    persistence:
      enabled: true
      existingClaim: nmd-storage-minio-claim
    ingress:
      enabled: true
      hosts:
        - "mimio-nmd.crazyzone.be"
      tls:
        - secretName: tls-secret
          hosts:
            - "minio-nmd.crazyzone.be"
    consoleIngress:
      enabled: true
      hosts:
        - "minio-nmd-console.crazyzone.be"
      tls:
        - secretName: tls-secret
          hosts:
            - "minio-nmd-console.crazyzone.be"
    tls:
      enabled: false
      #certSecret: secret-tls-minio
  mailhog:
    enabled: true
    ingress:
      hosts:
        - host: "mail-nmd.crazyzone.be"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: tls-secret
          hosts:
            - "mail-nmd.crazyzone.be"
