nomadesk:
  global:
    registry: "registry.nomadesk.com/nomadesk"
    imagePullSecrets:
      - registry-nomadesk-cred
  nomadesk:
    hostname: "nmd.crazyzone.be"
    version: "dev"
    admin:
      autocreate: true
      email: "nico.vanlaerebeke@nomadesk.com"
      enablePartnerPortal: true
    billing:
      enable: true
    billingapi:
      enable: true
    devdocs:
      enabled: true
    licenseserver:
      enabled: true
    shorturl:
      enabled: true
    storage:
      enablePersistentStorage: true
      existingVolumeClaim: nmd-storage-claim
    syncserver:
      port:
        type: Ingress
    ingress:
      enabled: true
      tlssecret: secret-tls
    db: 
      autocreate: true
      postgresHost: "nmd.crazyzone.be"
      postgresPort: 30000
      postgresDbPassword: "password"
    redis:
      hostname: "nmd.crazyzone.be"
      port: 30002
      password: "password"
  postgresql:
    enabled: true
    auth:
      secretKeys:
        adminPasswordKey: "postgresql-password"
    global:
      postgresql:
        auth:
          existingSecret: "nomadesk-postgres-password"
    image:
      tag: 16
    primary:
      service:
        type: NodePort
        nodePorts:
          postgresql: 30000
      persistence:
        enabled: true
        existingClaim: nmd-storage-db-claim-new
  redis:
    enabled: true
    master:
      persistence:
        enabled: false 
  minio:
    enabled: false
  mailhog:
    enabled: true
    ingress:
      hosts:
        - host: "mail-nvl.crazyzone.be"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: tls-secret
          hosts:
            - "mail-nmd.crazyzone.be"