immich:
  global:
    security:
      allowInsecureImages: true
  controllers:
    main:
      containers:
        main:
          env:
            DB_HOSTNAME: postgresql.services.svc.cluster.local
            DB_USERNAME: immich
            DB_DATABASE_NAME: immich
            DB_PASSWORD:
              valueFrom:
                secretKeyRef:
                  name: immich-secrets
                  key: password            
          image:
            tag: v2.7.5
  immich:
    persistence:
      library:
        existingClaim: immich-immich-claim  
  valkey:
    enabled: true
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: immich-redis-claim  # re-use your old redis PVC if you want

  server:
    ingress:
      main:
        enabled: true
        hosts:
          - host: photos.crazyzone.be
            paths:
              - path: "/"
        tls: 
        - secretName: crazyzone-be-tls
          hosts:
          - photos.crazyzone.be

  machine-learning:
    controllers:
      main:
        containers:
          main:
            env:
              MACHINE_LEARNING_REQUEST_THREADS: "6"
              MACHINE_LEARNING_WORKERS: "2"
    persistence:
      cache:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: immich-ml-cache-claim
