apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unifi
spec:
  tls:
    - hosts:
      - wifi.crazyzone.be
      secretName: wifi.crazyzone.be
  rules:
    - host: wifi.crazyzone.be
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unifi
                port:
                  number: 8880
