apiVersion: v1
kind: Service
metadata:
  name: unifi
spec:
  ports:
    - name: main
      protocol: TCP
      port: 8443
      targetPort: 8443
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-comm
spec:
  ports:
    - name: comm
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-guestportal
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8880
      targetPort: 8880
    - name: websecure
      protocol: TCP
      port: 8843
      targetPort: 8843
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-speedtest
spec:
  ports:
    - name: speedtest
      protocol: TCP
      port: 6789
      targetPort: 6789
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-stun
spec:
  ports:
    - name: stun
      protocol: UDP
      port: 3478
      targetPort: 3478
  type: ClusterIP
