#!/bin/bash
ROOT="$(cd "." >/dev/null 2>&1 && pwd)"

. $ROOT/vendor/k3s-base/include.sh
. $ROOT/lib/include.sh

case $1 in
configure)
  echo "Configure Environment"
  configure
  ;;
*)
  echo "Please provide a valid action"
  exit 1
  ;;
esac

