apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-password
  namespace: nomadesk
spec:
  encryptedData:
    postgres-password: AgAp+iF3b5AHBzW0EqNiU/sVym/ryV8dkO3bmQAxqXvxTmXMjYAbvp+AoUVF/dYID0LW4TRQeuBKS0d5sLCUWMmMiJufNAuNgkpe6lZtUJ2VFieVv9FyERiPCrYiXeEMZ443moDji+bDx8/WAl5wSSnAesGQUkQXMSbF5LuBOXvuhfVxIrlIvkwfH63oCDf6tPpnmwkXYY3vAQ4VeWS3+hfsF1ha7KRYlvsUfevcUnxIyZkoGcThfcNWhfm3N7WW9m3fiJHSYo3/h4gnixj4aeWHzc08RxhANvpGsm/Tof+BCu2MZvbSMYkHZHkjuf48+cgZClrrEhoQdXK0xcJlxdYhxyGUTN5hDfgAReZGRPF0FGUPDyPVJmNwD4vXKBvSyJOR7pCcNPEed6n0rFk3MwCzOoYL/0VuUio+9NHo7ChK6PBcSbJUYnzPiqkleY7mXNL4mhROy0VlsvxFzrKokvfgGVg2gfdgz804L2O4gqi6eCQX5Np/hmx9X8P6X7AXsNSjlrg1KP1KiWno+sLILoo5npWUeQ97M2gYg5E3AF4KpZ8gfKvijvIA+jHWAP7DgaRLhWJ7lsQ8FpRIfbl33g6lTa3OwHTvTtLoHXAgeo3OZWjVAu06Dx0fkNl5jLYqovLJz7m4hRmhEUj0l1UT6E2HQqHiQZsvDHwee+KgnP5cI6lkUdT45l71pF6SLeU3W2ZZla4O69AZgAu2DP/PdnkP4pj4MfITMWw=
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-password
      namespace: nomadesk
    type: Opaque