apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-storage
  namespace: services
  labels:
    app: redis-storage
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: nas.crazyzone.be
    path: "/volume1/docker-storage/backend-services/redis"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-storage-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: redis-storage
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem