apiVersion: v1
name: registry-ui
version: 0.0.4
appVersion: 0.0.4
description: ui for the container registry
dependencies:
  - name: docker-registry-ui
    version: "0.4.1"
    repository: "https://helm.joxit.dev"
