apiVersion: v1
name: euro-office
version: 6.0.0-test.1
appVersion: 9.3.1
description: Euro-Office Umbrella Chart
dependencies:
  - name: docs
    version: "6.0.0-test.1"
    repository: "oci://ghcr.io/nvanlaerebeke/charts"