docs:
  connections:
    dbHost: "postgresql.services.svc.cluster.local"
    dbUser: eurooffice
    dbName: eurooffice
    dbExistingSecret: euro-office-passwords
    redisHost: valkey-standalone.services.svc.cluster.local
    redisDBNum: "0"
    redisNoPass: true
    amqpHost: eurooffice-rabbitmq
    amqpUser: default_user_yZTHVOy1EN96hiJd36z
    amqpExistingSecret: euro-office-passwords
  persistence:
    existingClaim: "euro-office-storage-files-claim"
    customResources:
      existingClaim: "euro-office-storage-custom-resources-claim"
    buffer:
      existingClaim: "euro-office-storage-buffer-claim"
    runtimeConfig:
      enabled: true
      existingClaim: "euro-office-storage-runtime-config-claim"
  log:
    level: DEBUG
  wopi:
    enabled: true
    keys:
      generation: true
  extraConf:
  #  configMap: euro-office-local-config
  #  filename: local.json
    settings:
      storage:
        externalHost: https://eurooffice.crazyzone.be
      services:
        CoAuthoring:
          autoAssembly:
            enable: true
            interval: 5s
            step: 5s
          server:
            savetimeoutdelay: 2s
            editorDataStorage: editorDataRedis
  images:
    tag: latest
  runtimeOverrides:
    configMap: runtime-config-override
    filename: runtime.json
    settings: {}
  docservice:
    replicas: 1
    image:
      repository: harbor.crazyzone.be/crazyzone-public/cluster-docs
      tag: latest
      pullPolicy: Always
    extraEnvVars:
      - name: COMPANY_NAME
        value: euro-office
    extraVolumes:
      - name: document-formats
        configMap:
          name: euro-office-document-formats
          items:
            - key: onlyoffice-docs-formats.json
              path: onlyoffice-docs-formats.json
    #  - name: runtime-config-override
    #    configMap:
    #      name: runtime-config-override
    extraVolumeMounts:
      - name: document-formats
        mountPath: /var/www/euro-office/documentserver/document-formats
        readOnly: true
      #- name: runtime-config-override
      #  mountPath: /var/www/euro-office/config/runtime.json
      #  subPath: runtime.json
      #  readOnly: true
  converter:
    replicas: 1
    extraVolumes:
      - name: runtime-config-override
        configMap:
          name: runtime-config-override
    extraVolumeMounts:
      - name: runtime-config-override
        mountPath: /var/www/euro-office/config/runtime.json
        subPath: runtime.json
        readOnly: true
    image:
      repository: harbor.crazyzone.be/crazyzone-public/cluster-docs
      tag: latest
      pullPolicy: Always
    extraEnvVars:
      - name: COMPANY_NAME
        value: euro-office
  proxy:
    image:
      repository: harbor.crazyzone.be/crazyzone-public/cluster-docs
      tag: latest
      pullPolicy: Always
    extraEnvVars:
      - name: COMPANY_NAME
        value: euro-office
  adminpanel:
    enabled: true
    image:
      repository: harbor.crazyzone.be/crazyzone-public/cluster-docs
      tag: latest
      pullPolicy: Always
    extraEnvVars:
      - name: COMPANY_NAME
        value: euro-office
  example:
    enabled: true
  tests:
    image:
      repository: harbor.crazyzone.be/crazyzone-public/cluster-utils
  install:
    job:
      image:
        repository: harbor.crazyzone.be/crazyzone-public/cluster-utils
        tag: v9.3.4-hotfix.1
  upgrade:
    job:
      image:
        repository: harbor.crazyzone.be/crazyzone-public/cluster-utils
  rollback:
    job:
      image:
        repository: harbor.crazyzone.be/crazyzone-public/cluster-utils
  delete:
    job:
      image:
        repository: harbor.crazyzone.be/crazyzone-public/cluster-utils
  clearCache:
    job:
      image:
        repository: harbor.crazyzone.be/crazyzone-public/cluster-utils
  grafanaDashboard:
    job:
      image:
        repository: harbor.crazyzone.be/crazyzone-public/cluster-utils
  wopiKeysGeneration:
    job:
      image:
        repository: harbor.crazyzone.be/crazyzone-public/cluster-utils
  wopiKeysDeletion:
    job:
      image:
        repository: harbor.crazyzone.be/crazyzone-public/cluster-utils
  ingress:
    enabled: true
    ingressClassName: traefik
    ssl:
      enabled: true
      secret: crazyzone-be-tls
    host: "eurooffice.crazyzone.be"
  #upgrade:
  #  existingConfigmap:
  #    dsStop: euro-office-pre-upgrade
