apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv-name
  namespace: monitoring
  labels:
    app: pihole
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce # required
  nfs:
    server: 192.168.5.50 #use IP as pihole is the DNS
    path: "/volume1/docker-storage/pihole"
