apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-redis
  labels:
    app: immich-redis
spec:
  storageClassName: standard
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: nas.crazyzone.be
    path: "/volume1/docker-storage/immich/redis"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-redis-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: immich-redis
  resources:
    requests:
      storage: 500Gi
  volumeMode: Filesystem
