apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
data:
  config.yml apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
data:
  config.yml: |
    storage:
      delete:
        enabled: true
