apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
data:
  config.yml apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
data:
  config.yml: |
    storage:
      delete:
        enabled: true
    http:
      headers:
        X-Content-Type-Options: [nosniff]
        Access-Control-Allow-Origin: ['*']
