apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
  name: registry
spec:
  selector:
    app: registry
  type: ClusterIP    
  ports:
  - name: registry
    port: 80
    protocol: TCP
    targetPort: 5000
  