apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-storage
  namespace: services
  labels:
    app: db-storage
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/postgres/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-storage-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: db-storage
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem