apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pxe-www
  name: pxe-www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pxe-www
  template:
    metadata:
      labels:
        app: pxe-www
    spec:
      containers:
      - image: registry.crazyzone.be/ipxe:latest
        name: pxe-www
        ports:
        - containerPort: 80
          name: pxe-www
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5