apiVersion: v1
name: gogs
version: 0.0.1
appVersion: 0.0.1
description: Git server for crazyzone
dependencies:
  - name: gogs
    version: "0.1.3"
    repository: "https://keyporttech.github.io/helm-charts/"
  - name: postgresql
    version: "12.1.0"
    repository: "https://charts.bitnami.com/bitnami/"
