{
 "title": "Vulnerabilities",
 "tags": [ "home" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values(vulnerability,project)"
    }
   },
   {
    "name": "repository",
    "label": "repository",
    "query": {
     "query": "label_values(vulnerability,repository)"
    }
   },
   {
    "name": "tag",
    "label": "tag",
    "query": {
     "query": "label_values(vulnerability,tag)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Vulnerability Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Critical Vulnerabilities",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(vulnerability{type=\"Critical\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "High Vulnerabilities",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum(vulnerability{type=\"High\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Medium Vulnerabilities",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum(vulnerability{type=\"Medium\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Low Vulnerabilities",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum(vulnerability{type=\"Low\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Project Vulnerabilities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Critical",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "vulnerability{project=~\"$project\", repository=~\"$repository\", tag=~\"$tag\", type=\"Critical\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "High",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "vulnerability{project=~\"$project\", repository=~\"$repository\", tag=~\"$tag\", type=\"High\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "vulnerability{project=~\"$project\", repository=~\"$repository\", tag=~\"$tag\", type=\"Medium\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Low",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "vulnerability{project=~\"$project\", repository=~\"$repository\", tag=~\"$tag\", type=\"Low\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}