apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ $.Values.name }}
  name:  {{ $.Values.name }}
spec:
  replicas:  {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app:  {{ $.Values.name }}
  template:
    metadata:
      labels:
        app:  {{ $.Values.name }}
    spec:
      tolerations:
      - key: "type"
        value: "power"
        operator: "Equal"
        effect: "NoSchedule"
      affinity:
        nodeAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution: 
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In 
                values:
                - power
      containers:
      - image: registry.crazyzone.be/powerreadout:0.0.9
        name:  {{ $.Values.name }}
        volumeMounts:
        - mountPath: /dev/ttyUSB
          name: dev-usb0
        securityContext:
          privileged: true
        ports:
        - containerPort: 80
          name: {{ $.Values.name }}
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: dev-usb0
        hostPath:
          path: /dev/ttyUSB0
