apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'postgresql'
spec:
  project: 'default'
  destination:
    name: ''
    namespace: 'services'
    server: 'https://kubernetes.default.svc'
  source:
    path: 'applications/charts/backend-services/postgresql'
    repoURL: '$GIT_URL'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true.
      - ServerSideApply=true