apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-initial-root-password
  namespace: gitlab
spec:
  encryptedData:
    password: AgAiEtAeUS0NVNfp3SiVkibCxyFf4HZseFX5djaXqPJjdyhfeb1BE0E4loJvH4S5M9QlfLm7bBTrkuh0dUSGlbidtBUrorCRgcQz7IDV7V4VORTw91P4OJ7VVjtSWkDsbKkRPhuenXwo9JMBq00wb260iNs+Z6k/F1ic0BpO5tGT6fl5/jti7xOcX1LegW0TXR154zpy/YGca7pE/WOFT/lcE8LJUNWj7gF83AsnU/3jyf0bAmY+3iZz8I+QbDT5G+rcICyaeAgA6ie8IrynJvudIb5JpPlTw0JPKzY10GhRoxGMUq4LbSkAdY4th2TDeHw9xDMwWx2PjxNVvXGSFDhWfNVQ9phHe7GHioAzijklqHl/7Ne2qn0xjXXfJMxkHQ48BCsdkuT0q3AL7jR4ChrDeW18qND/MMDZlDIfQexlUFtFgcJ5Ya6/hm64ph/gKUI2pMdr+QWnODP/JUjvg/aW074H1fmJXgYKcFojMv83b/432KPSstZj68zSRImtqSE3EYs4rjptub/iT4AB/ml/ki8WPNyGzUck5B4X/JOdc2DXO8Bd0n0CxEhsgDHxm3R/FyRy+lkbZvW700dNVBgfaCr68XsEqUcQ+eFEgufdfmkBBb+rwksw2ZXUE7tAknO6SgGJ8tMkOg8YWT/w1DiOqgrU42bCccrHkzn84Js8tM0n7pPHHhbHisDAwg1y8nMV28gxg/IQ8bmw8+/NqOI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitlab-initial-root-password
      namespace: gitlab
    type: Opaque
