openproject:
  ingress:
    enabled: true
    host: "openproject.crazyzone.be"
    tls:
      enabled: true
      secretName: "crazyzone-be-tls"
  openproject:
    admin_user:
      password: "admin"
      password_reset: "true"
      name: "OpenProject Admin"
      mail: "nico.vanlaerebeke@gmail.com"
  persistence:
    enabled: false
  s3:
    enabled: true
    auth:
      existingSecret: openproject-secrets
    bucketName: open-project
    host: minio.crazyzone.be
    port: 9000
  postgresql:
    bundled: false
    connection:
      host: "postgresql.services.svc.cluster.local"
      port: 5432
    auth:
      existingSecret: "openproject-secrets"
      secretKeys:
        adminPasswordKey: "postgres-password"
        userPasswordKey: "password"      