apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "ingress-home-assistant"
spec:
  tls:
    - secretName: secret-tls
      hosts:
      - home-assistant.crazyzone.be
  rules:
    - host: home-assistant.crazyzone.be
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: home-assistant
                port:
                  number: 8123