apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: server-route
spec:
  entryPoints:
    # Defined in the traefik configuration, e.g.
    # --entrypoints.websecure.address=:8888
    - websecure
    - web
  routes:
    - match:  Host(`home-assistant.crazyzone.be`)
      middlewares:
        - name: server-headers
      kind: Rule
      services:
        - name: homeassistant-home-assistant
          port: 8123
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: server-headers
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"