apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant
  namespace: home
  labels:
    app: home-assistant
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: nas.crazyzone.be
    path: "/volume1/docker-storage/home-assistant"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-claim
  namespace: home
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: home-assistant
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem