gitea:
  ingress:
    enabled: true
    hosts:
      - host: git.crazyzone.be
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: chart-example-tls
        hosts:
          - git.crazyzone.be

  persistence:
    enabled: true
    existingClaim: gitea-postgres-storage-claim

  admin:
    existingSecret: gitea-admin-secret
    email: "nico.vanlaerebeke@gmail.com"

postgresql:
  enabled: true
  global:
    postgresql:
      postgresqlDatabase: gitea
      postgresqlUsername: gitea
      postgresqlPassword: gitea
      servicePort: 5432
  persistence:
    size: 10Gi