gitea:
  ingress:
    enabled: true
    hosts:
      - host: git.crazyzone.be
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: chart-example-tls
        hosts:
          - git.crazyzone.be

  persistence:
    enabled: true
    existingClaim: gitea-storage-claim

  postgresql:
    enabled: true
    global:
      postgresql:
        postgresqlDatabase: gitea
        postgresqlUsername: gitea
        postgresqlPassword: gitea
        servicePort: 5432
    persistence:
      existingClaim: gitea-postgres-storage-claim
    selector:
      matchLabels:
        app: gitea-postgres-storage

  gitea:
    admin:
      existingSecret: gitea-admin-secret
      email: "nico.vanlaerebeke@gmail.com"
