gitea:
  ingress:
    enabled: true
    hosts:
      - host: git.crazyzone.be
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: chart-example-tls
        hosts:
          - git.crazyzone.be
  service:            
    ssh:
      type: NodePort
      nodePort: 30022
      port: 22
      clusterIP: 
  persistence:
    enabled: true
    create: false
    claimName: gitea-storage-claim
    existingClaim: gitea-storage-claim
    primary:
      existingClaim: gitea-storage-claim
  postgresql:
    enabled: false
  postgresql-ha:
    enabled: false
  redis-cluster:
    enabled: false
  redis:
    enabled: true
  gitea:
    admin:
      existingSecret: gitea-admin-secret
      email: "nico.vanlaerebeke@gmail.com"
    config:
      server: 
        ROOT_URL: https://git.crazyzone.be
