gitea:
  image:
    tag: ":1"
    rootless: true
  ingress:
    enabled: true
    hosts:
      - host: git.crazyzone.be
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: chart-example-tls
        hosts:
          - git.crazyzone.be
  service:            
    ssh:
      type: NodePort
      nodePort: 30022
      port: 22
      clusterIP: 
  persistence:
    enabled: true
    existingClaim: gitea-storage-claim

  postgresql:
    enabled: true
    global:
      postgresql:
        auth:
          postgresqlDatabase: gitea
          postgresqlUsername: gitea
          postgresqlPassword: gitea
    persistence:
      existingClaim: gitea-postgres-storage-claim
    selector:
      matchLabels:
        app: gitea-postgres-storage

  gitea:
    admin:
      existingSecret: gitea-admin-secret
      email: "nico.vanlaerebeke@gmail.com"
