apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: secret-tls
  namespace: default
spec:
  additionalOutputFormats:
    - type: CombinedPEM
  dnsNames:
    - "crazyzone.be"
  issuerRef:
    kind: ClusterIssuer
    name: acme-issuer-staging
  secretName: secret-tls