apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: secret-tls
  namespace: default
spec:
  additionalOutputFormats:
  - type: CombinedPEM
  secretName: secret-tls
  issuerRef:
    name: hetzner-acme-issuer-prod
    kind: ClusterIssuer
  dnsNames:
    - "crazyzone.be"
    - "*.crazyzone.be"
