apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nomadesk-nl-tls
  namespace: default
spec:
  additionalOutputFormats:
  - type: CombinedPEM
  secretName: nomadesk-nl-tls
  issuerRef:
    name: godaddy-acme-issuer-staging
    kind: ClusterIssuer
  dnsNames:
    - "*.nomadesk.nl"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "default,argocd,home,jenkins,minio,monitoring,nomadesk,nomadesk-apis,operations,power,rancher,registry,cert-manager"  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "default,argocd,home,jenkins,minio,monitoring,nomadesk,nomadesk-apis,operations,power,rancher,registry,cert-manager" # Control auto-reflection namespaces