apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-secret
  namespace: registry
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgCq672k/Spld6NT9KimeymWZMh8N97EffwDoOJrx49UF24pHJLUd8tlnEWklyg5Zqx52qcT3Ay/ywSjTy+DqA4P0XPjwMqjrw3kl3D23xvh79+iJjJ8trYjylYcQ2jSg3aGu32jj744/pF5WHnXW6ll1UTQrXtT8oeZCzehf/nnH3YnjSoMQE0amMR8mWJ0U3EPnKstBXj7niu2oIcwn/Nm21Ahrg6CWGkLPzP8J6Os1fNwSP8DiCFSxPAvJzlqbOEmC89TVBDhc17kc3qF4z89WMkwYAoQsWXRCD2KA/p1FIO7U8ktHnXA2v97GHWT2qcPlnRVHwLxMQHP2axL8z3S+beW235V3Wgn7S2saLrgacm9+Z6NcIFcz1FF/PIB6qjihzSMrbspIr9hy5Szt3LBE2PzB0dufkM7SVYn7fgyQt/q1gfQpnbttWzQR0vpOwHQmVhzH+GhKosePJumh6gvbgnoAmrkwQqPlPnW1osJ7K/SkboMeQUXTlJTjMo+oGuKMK7A03MycM1lzBTIDFVa3+gi7lqnzPnTN+7hleBYuTg3NMTCxesKw0T7vbwtPynZ073b/wEdauaIOesRNH4cL1xu0U/GvptzHcdaypBkX0jbjj31TVOdaS5Kxzr0I6CypOk++q1RbRrcPAX0GdBivXVcxPYjwGfJudfU3qCIZVHSk1O1F0Y8xmXMTkOQQpL5bOGzhk/cZzP2vzrkeA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: harbor-secret
      namespace: registry
    type: Opaque
