# Default values for artifactory-oss.
# This is a YAML-formatted file.

# Beware when changing values here. You should know what you are doing!
# Access the values with {{ .Values.key.subkey }}

# This chart is based on the main artifactory chart with some customizations.
# See all supported configuration keys in https://github.com/jfrog/charts/tree/master/stable/artifactory

## All values are under the 'artifactory' sub chart.
artifactory-oss:
  artifactory:
    ## Ingress
    ## See full list of supported Ingress options and documentation in artifactory chart: https://github.com/jfrog/charts/tree/master/stable/artifactory
    ingress:
      enabled: true
      hosts:
        - artifactory.crazyzone.be
      tls:
        - secretName: secret-tls
          hosts:
            artifactory.crazyzone.be     
    artifactory:
      unifiedSecretInstallation: false
      global:
        ## Artifactory
        ## See full list of supported Artifactory options and documentation in artifactory chart: https://github.com/jfrog/charts/tree/master/stable/artifactory
        nginx:
          enabled: false  
      persistence:
        enabled: true
        existingClaim: artifactory-storage-claim
        customBinarystoreXmlSecret: ""

      postgresql:
        enabled: true
        persistence:
          existingClaim: artifactory-postgres-storage-claim
