apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'cert-manager-openprovider-webhook'
spec:
  project: 'cert-manager'
  destination:
    name: ''
    namespace: 'cert-manager'
    server: 'https://kubernetes.default.svc'
  source:
    path: 'applications/charts/cert-manager/cert-manager-openprovider-webhook'
    repoURL: '$GIT_URL'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
