apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-storage
  namespace: minio
  labels:
    app: minio-storage
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: nas.crazyzone.be
    path: "/volume1/docker-storage/backend-services/minio"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-storage-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: minio-storage
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
