apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'harbor'
spec:
  project: 'operations'
  destination:
    name: ''
    namespace: 'registry'
    server: 'https://kubernetes.default.svc'
  source:
    path: 'applications/charts/registry/harbor-vulnerability-exporter'
    repoURL: '$GIT_URL'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
