apiVersion: batch/v1
kind: CronJob
metadata:
  name: almalinux-9-reposync
spec:
  schedule: 45 2 * * *
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 500
      template:
        spec:
          imagePullSecrets:
            - name: registry-crazyzone-cred-home-docs
          volumes:
          - name: host-storage
            persistentVolumeClaim:
            claimName: almalinux-claim
          containers:
            - name: almalinux-9-reposync
              image: harbor.crazyzone.be/crazyzone/almalinux9-reposync
              imagePullPolicy: Always
              command: ["sleep"]
              args: ["infinity"]
              volumeMounts:
              - name: host-storage
                mountPath: /mnt
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
