apiVersion: v1
kind: PersistentVolume
metadata:
  name: almalinux
  labels:
    app: almalinux
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: nas.crazyzone.be
    path: "/volume1/docker-storage/host/mirror/almalinux/9"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: almalinux-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: almalinux
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem