apiVersion: v1
kind: PersistentVolume
metadata:
  name: host
  labels:
    app: host
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: nas.crazyzone.be
    path: "/volume1/docker-storage/host"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: host
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem