netbox:
  superuser:
    existingSecret: "netbox-secrets"
  admins: [ 'Nico Van Laerebeke', "nico.vanlaerebeke@gmail.com" ]
  email:
    server: smtp.gmail.com
    port: 587
    existingSecretName: "netbox-secrets"
    existingSecretKey: email_password
  loginRequired: true
  timeZone: CET
  existingSecret: ""
  persistence:
    enabled: true
    existingClaim: "netbox-storage-data-claim"
  reportsPersistence:
    enabled: true
    existingClaim: "netbox-storage-reports-claim"
  ingress:
    enabled: true
    hosts:
      - host: netbox.crazyzone.be
        paths: 
        - /
    tls: 
      - secretName: secret-tls
        hosts:
          - netbox.crazyzone.be
  postgres:
    enabled: false
  externalDatabase:
    host: postgresql.services.svc.cluster.local
    port: 5432
    existingSecretName: "netbox-secrets"
    existingSecretKey: postgresql-password
  redis:
    enabled: false
  tasksRedis:
    host: redis-master.services.svc.cluster.local
    existingSecretName: "netbox-secrets"
    existingSecretKey: redis-password
    database: 1
  cachingRedis:
    database: 2
    host: redis-master.services.svc.cluster.local
    existingSecretName: "netbox-secrets"
    existingSecretKey: redis-password
