apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-postgres-storage
  namespace: operations
  labels:
    app: gitea-postgres-storage
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: nas.crazyzone.be
    path: "/volume1/docker-storage/gitea/postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgres-storage-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: gitea-postgres-storage
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem