apiVersion: v1
kind: PersistentVolume
metadata:
  name: kiwi-db
  labels:
    app: kiwi-db
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/kiwi/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiwi-db-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: kiwi-db
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem