apiVersion: v1
kind: PersistentVolume
metadata:
  name: kiwi-uploads
  labels:
    app: kiwi-uploads
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/kiwi/uploads"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiwi-uploads-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: kiwi-uploads
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem