apiVersion: v1
kind: ConfigMap
metadata:
  name: repo-sync-ub20.04-mirror
data:
  mirror.list: |
    ############# config ##################
    #
    set base_path    /mnt/apt-mirror
    #
    set mirror_path  $base_path/mirror
    set skel_path    $base_path/skel
    set var_path     $base_path/var
    # set cleanscript $var_path/clean.sh
    # set defaultarch  <running host architecture>
    # set postmirror_script $var_path/postmirror.sh
    # set run_postmirror 0

    set nthreads     20
    set _tilde 0
    set defaultarch amd64
    #
    ############# end config ##############

    deb http://be.archive.ubuntu.com/ubuntu focal main restricted
    deb http://be.archive.ubuntu.com/ubuntu focal-updates main restricted
    deb http://be.archive.ubuntu.com/ubuntu focal universe
    deb http://be.archive.ubuntu.com/ubuntu focal-updates universe
    deb http://be.archive.ubuntu.com/ubuntu focal multiverse
    deb http://be.archive.ubuntu.com/ubuntu focal-updates multiverse
    deb http://be.archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
    deb http://security.ubuntu.com/ubuntu focal-security main restricted
    deb http://security.ubuntu.com/ubuntu focal-security universe
    deb http://security.ubuntu.com/ubuntu focal-security multiverse

    #extra
    deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable

    clean http://be.archive.ubuntu.com/ubuntu
    clean http://security.ubuntu.com/ubuntu
    clean https://download.docker.com/linux/ubuntu