minio:
  mode: standalone
  replicas: 1

  persistence:
    enabled: true
    existingClaim: minio-storage-claim

  ingress:
    enabled: true
    path: /
    hosts:
      - minio.crazyzone.be
    tls: 
      - secretName: crazyzone-be-tls
        hosts:
          - minio.crazyzone.be
  consoleIngress:
    enabled: true
    path: /
    hosts:
      - minio-console.crazyzone.be
    tls: 
      - secretName: crazyzone-be-tls
        hosts:
          - minio-console.crazyzone.be

  resources:
    requests:
      memory: 512Mi