apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Chart.Name | lower }}-storage-zigbee2mqtt
  labels:
    app: {{ $.Chart.Name | lower }}-storage-zigbee2mqtt
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: nas.crazyzone.be
    path: "/volume1/docker-storage/home/zigbee2mqtt"