apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Chart.Name | lower }}-storage-zigbee2mqtt
  labels:
    app: {{ $.Chart.Name | lower }}-storage-zigbee2mqtt
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: nas.crazyzone.be
    path: "/volume1/docker-storage/home/zigbee2mqtt"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume-home-zigbee2mqtt-0
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: {{ $.Chart.Name | lower }}-storage-zigbee2mqtt
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
