apiVersion: v2
name: valkey-standalone
description: Standalone Valkey deployment using the official Valkey Helm chart
type: application
version: 0.1.0
appVersion: "9.1.2"
dependencies:
  - name: valkey
    alias: valkeyStandalone
    version: "0.12.0"
    repository: "https://valkey.io/valkey-helm/"
