apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kickstart-www
  name: kickstart-www
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kickstart-www
  template:
    metadata:
      labels:
        app: kickstart-www
    spec:
      containers:
      - image: registry.crazyzone.be/kickstart:latest
        name: kickstart-www
        ports:
        - containerPort: 80
          name: kickstart-www
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5          