apiVersion: v1
description: A Helm chart for the Hetzner DNS webhook for cert-manager
name: cert-manager-webhook-hetzner
version: 1.2.2
dependencies:
  - name: cert-manager-webhook-hetzner
    version: "1.2.2"
    repository: "https://vadimkim.github.io/cert-manager-webhook-hetzner"