# kubernetes deployment template
# prepare a namespace on your cluster first like libretranslate-prod
apiVersion: v1
kind: ConfigMap
metadata:
  name: libretranslate-config
data:
# list loaded languages or leave empty to load all
  langs: {{ .Values.langs }}
  ltapikey: {{ .Values.apikey }}