apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-secret
  namespace: operations
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgAJn/CqDI2q7suR/XOk4kxdj3bInUrkmx+b464ACfZBdfTdlO042ZCqdlrh38ozRM6xLtKHLByIr+TqQ8sLWds7IQyzMZ7wR2T8BZ76JMYOBakFWf9ptK6IhLdWOstjYdjdGIR08iOkT8nj2Y11wLAi+xaaXXGgg88usYnolyXxCAFVn4ZhNgf8/brnmgd/ZV8KZTBjPCmqk9fW6zjL21obx0fVGpoaKw4DLYo2pjqWP1VroGWK28pkfnLzd44C2PwVtblwsBY+KKUAfLD34WbJmA6e6/OLp0tVNzWOe2EyXJ7PokOEnJ5ONs5EN2cdRJV6w1sBYdtqsVU/GkgNA/YIj/3FAc8j56RbxbMyFlDJwvjAt2MurU5xX+gP69bzzcq1KykzmvcRJUQBqZ6Kyx7sZ0XJ3d3xgjgM0esx7TyVHoS2D4MxnF3oQssYmiP8HHbH/wJSL4VC8E5i6Ty/ub7L2zpHqZodT/u1hz5xCdgtP6AWAmnFGb19Z1b/j0MwcPDckUmkfwAc6DQhaFbIFq7jl+DUY/tFMzfhNogzlU+xiytSa3A6k8BBkoNc1WIeZi4cozPcjNyWVWM3h/+hrRtP1qkILmaTRn7113ztC7T+//0MQpPLLllFcrjOaEfi/K8vBzrH8/vvLsaxmKPUBlNiiq5wnAtXwaHrxMtViFJvslsVj5QwkC+aIC+wya9ELm4SQ6Pd/b3l7evLo3ci0g==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: harbor-secret
      namespace: operations
    type: Opaque
