apiVersion: v1
kind: Service
metadata:
  name: torrent
spec:
  selector:
    app: torrent
  type: ClusterIP
  ports:
    - name: rutorrent-port
      port: 80
      targetPort: 80
    - name: incoming-port
      port: 49161
      targetPort: 49161
    - name: dht-port
      port: 49160
      protocol: UDP