apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: digitalocean-dns
  namespace: cert-manager
spec:
  encryptedData:
    access-token: AgAfINtZ0TAl/iRQlkKv7Pkk6N0c7qOvWLpEHs343B6GntCAxMPbmgGw8ANHr8klC7NfCU5M/Z6qUNGZweId28MdiDR8gRBCTZBzeRRwH+wKVCR//XEPyslv5QxKhQMnHbII/tPPf3yOkpNB4vx3f+LXRZ8F3lULQH0iWupVuoQg8IYXLCjjBhiiJ6v6TFWXST3/y7d3p2DK3Gn8kex+XESd9rLq29I9jF9MqkQDSwKLcYz0pPU5K1Fj2W2egOpECik5a1sYqR2ZtmMElMEARbPUZqt9aorJj7NUeeYDrSHx8v+zdHuC/rYreur/Vqu6Ud4Y+/JUmXqDvbNNLnTYEpfzqqy9Z/d7bwJFrIMKm0QWuN95qtL9UyCxl7x2XBHKwJ23eXQoRz8Tz3yRGmi+RcOMmqqsUIXMIByhINaffIY/ifXb/yuB2saEFjlxAlobBqb/FquAvkf9GsccTnGVi8o6m7K/qJXyzPuSX5Oqe7TOksKFq5W0X3tyoZqSEnqCv3I0X18x0S0gVp1+kFeizt8qkd5IFlW/QHC/DBKs6SnPRnP+u6GGzon4a7UNR4Mvkol7OtYAgTC/t4ftfvyNE+nQIWqqivlc1PSe9RweZHN7TOCcGziK73WEAT2rmwoEiqMSCR5b/W2WjzkzfJ0xHQtA5fp36QZajsFyImYohVBQYhP6eD40feIoLXqz+aJQ1l8IZNYrhu5kTWxn4/Eisy8UGfSmRx3KMrkDbW0nPbMoS6EuKIrPxVbTZ4pBXCLbc9vA7LeIjtV0YlW0kd4BddEw9ko/r/7Evoc=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: digitalocean-dns
      namespace: cert-manager
    type: Opaque
