apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: godaddy-acme-issuer-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: nico.vanlaerebeke@gmail.com
    privateKeySecretRef:
      name: godaddy-letsencrypt-prod # staging or production
    solvers:
      dns01:
        webhook:
          groupName: acme.nomadesk.com
          solverName: godaddy
          config:
            apiKeySecretRef:
              name: godaddy-api-key
              key: token
            production: true
            ttl: 600