EOF apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: godaddy-acme-issuer-prod
spec:
  acme:
    # ACME Server
    # prod : https://acme-v02.api.letsencrypt.org/directory
    # staging : https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    # ACME Email address
    email: nico.vanlaerebeke@gmail.com
    privateKeySecretRef:
      name: godaddy-letsencrypt-prod # staging or production
    solvers:
      dns01:
        webhook:
          config:
            apiKeySecretRef:
              name: godaddy-api-key
              key: token
            production: true
            ttl: 600
          groupName: acme.nomadesk.com
          solverName: godaddy