apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rregistry-nomadesk-cred
  namespace: nomadesk
spec:
  encryptedData:
    .dockerconfigjson: AgCIiV9P7U+shooF66rZMtuUI/HFw388jPyZRLiFYsxm/2eYq95K/s43Yq82v7/F10kWO7+4fuKCDGO48YZx+uP3Db1T7reWIAFuGr07Jz/4IJvVDlU1DWEFUKozyWcuGIt2QVxyZq8UB3mBQZl1Q+A9WddZJHF0PyJUn25ASOIr5zpEt7KSiAFT4k4d0Gc4ajmKg+KpqzvY2i9RFB0/gL4PZC7qf/g8/0fJqz+ErG558b5PwyA9QJO1o7RseFWErQYniYhjMCcETtlzB+kXzRMzvhp9XkTw36uPfHraWuxswr9qWGJBIUAwm170Cvfmsp8ega+1B70TTlqHUHqNjlSj1wsHw0MuH4wtCCh/LWEWvVSNq5CKO9fvnSoXGK+jOr3z/2gJgZkwzjxcYlY5FTZTGS3cZTFub37oxtRuyjZ9IysJO5z36dh8ab4o8FoFTv8gTBONhXS5BtV90ayEfQLahosrd4bkeMvP/FbI4AirqapamCfCBn4CPtH3PNgqIQCLjtEC2FpeEAMzhQ7WvBVybieb698uZIMfrtm4aHnvc2YQWkDTIdQ2e2O6SSlxgFPu1bpMI7px7oZNZHngwrbo1FG0jKblUo7WLApFd6utmraPbmVCw5X45rx4TjGf0WYiumDm7Dvo9X0gfIPzVJPFoQVJkqXAc5bzJ311UvgFhlAD6hVldtV9r6tvuc57RaAFOXhYYPI4Tw25QwlvO811yGsOaRlXzxujxg9ly380gtM7Jh9KoAleSG2Oc+BxJyhcDQN86fMr6q/+hwRfowuVgzBrBkh64frRehTIqpQIuqJFjrgboUX1XUGoaSzuPlYNZMpaB9gTnV5wFsUtk11pB9TanjlG6C6TKQd1xnyqfcFq+DY3
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: rregistry-nomadesk-cred
      namespace: nomadesk
    type: kubernetes.io/dockerconfigjson
