apiVersion: v1
kind: PersistentVolume
metadata:
  name: nmd-storage-db
  namespace: nomadesk
  labels:
    app: nmd-storage-db
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: nas.crazyzone.be
    path: "/volume1/docker-storage/nomadesk/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nmd-storage-db-claim
spec:
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: nmd-storage-db
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
