apiVersion: v1
kind: PersistentVolume
metadata:
  name: nmd-storage-db-new
  labels:
    app: nmd-storage-db-new
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: nas.crazyzone.be
    path: "/volume1/docker-storage/nomadesk/db/nmd-new"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nmd-storage-db-claim-new
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: nmd-storage-db-new
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
