apiVersion: v1
kind: PersistentVolume
metadata:
  name: nmd-storage
  labels:
    app: nmd-storage
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: nas.crazyzone.be
    path: "/volume1/docker-storage/nomadesk/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nmd-storage-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: nmd-storage
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
