apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: standalone-password
  namespace: services
spec:
  encryptedData:
    default: AgCXhb8H0kliOhq1Bq9PQiOOiN+fmVRyHAzPw1IaW0riQOFugR23R4CYxpQ86scY01vbAbz8v3RCwV+KaKG4jnljpdCTUDFjLBZKxuK76uOLmElrab1atmOjrM7rSChe/6b/AkYUZQaeQX4/dfY1C+x9IHCJMUiDPQKcPNC0aJsTFZY541T7dIKBDSJzhJb0CIHUbosRwf0BQg1AsT7290ExmXWAAdgHdWp4+mhYscsWZ6XmACzGUUZs7Se4UatanYYfF7iZ1A61DL4rskukUGmG0p4DROgvhpBM1xttIhZaRPjFIgYuaJuP+ESr47UOApI1vJR/1ssPCBTcVGXz/n3nG7OJfk9QRfuvB4NwKKDc4mfwi4D08IG9zEdgyGcrAdXT83PLM3miQLVxqNy9t2f0W3iLOQWTmspDI+tnoHlp5y4vKHjy/HDN0RtC+VWofBu2D9AkSP5kUXpgWojZEoOqVuXlCjujQGVy1nj2aa+IvHXpu7Gt+a93n3HQscowBNyKDmEuBAJMaKJKWfX0VQaNqWF7zOR+J0rxT2rYjbox3NuMf9qBDTKx/LurXIIYW5UMdWgMapmujN+0Ie0bQkhHiCfFggjxducvBSMoa1islS7q2qpb22x2/g2j6XjaoIxNz6rS2eKPHUU6qzy8aI7nrh0b3tI4TqmTSop39LrbcL/vMU50NJ3OvHzYAtdSh6vY9i5PHthGfEK6ZY8z4qwMB9fthE99OzJx+B48dhaIHJZBvnTh3RW46hhE1sX4BywdrHH85OQ0ha3UZU+tU2n2
  template:
    metadata:
      creationTimestamp: null
      name: standalone-password
      namespace: services
    type: Opaque