apiVersion: v1
appVersion: "10.0.65"
description: reflector
name: reflector
version: 10.0.65
dependencies:
  - name: reflector
    version: "10.0.65"
    repository: "https://emberstack.github.io/helm-charts"