tlssecret: secret-tls
hostname: guacamole.crazyzone.be
guacamole:
  postgres:
    database: "guacamole"
    hostname: "guacamole-postgresql"
    password: "L6UwuxgrXH"
  service:
    port: 8080
  ingress:
    enabled: false
postgresql:
  global:
    postgresql:
      auth: 
        database: "guacamole"
        username: "guacamole"
        existingSecret: "guacamole-postgres-password"
  auth:
    secretKeys:
      adminPasswordKey: "postgresql-password"
      userPasswordKey: "postgresql-password"
  volumePermissions:
    enabled: true
  primary:  
    persistence:
      enabled: true
      existingClaim: guacamole-postgres-storage-claim
