{
 "title": "Power Usage",
 "tags": [ "home" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Plugs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rack",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "power_consumption{job=\"rack\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Desk Nico",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "power_consumption{job=\"nico\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Desk Tatjana",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "power_consumption{job=\"tatjana\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lego Display",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "power_consumption{job=\"lego_display\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Freezer + Fridge",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "power_consumption{job=\"fridge_freezer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Water Fountain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "power_consumption{job=\"water_fountain\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "House",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "l1_power_usage_value{instance=\"https://power-reader.crazyzone.be/metrics\", job=\"power-reader.crazyzone.be\", unit=\"Watt\"}"
      }
     ]
    },
    {
     "title": "Power Production",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "total_power_generated_value{instance=\"https://power-reader.crazyzone.be/metrics\", job=\"power-reader.crazyzone.be\", unit=\"Watt\"}"
      }
     ]
    },
    {
     "title": "Current (Ampere)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "l1_amperage_value{instance=\"https://power-reader.crazyzone.be/metrics\", job=\"power-reader.crazyzone.be\", unit=\"Ampere\"}"
      }
     ]
    },
    {
     "title": "Voltage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "l1_voltage_value{instance=\"https://power-reader.crazyzone.be/metrics\", job=\"power-reader.crazyzone.be\", unit=\"Volt\"}"
      }
     ]
    },
    {
     "title": "Gas Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "m3" } },
     "targets": [
      {
       "expr": "gas_used_value{instance=\"https://power-reader.crazyzone.be/metrics\", job=\"power-reader.crazyzone.be\", unit=\"CubicMeter\"}"
      }
     ]
    }
   ]
  }
 ]
}