{
 "title": "Sensors KVM",
 "tags": [ "home" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Temp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"pci0000:00_0000:00:18_3\", endpoint=\"metrics\", host=\"kvm\", instance=\"kvm.crazyzone.be:9100\", job=\"node-exporter\", sensor=\"temp1\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"pci0000:00_0000:00:18_3\", endpoint=\"metrics\", host=\"kvm\", instance=\"kvm.crazyzone.be:9100\", job=\"node-exporter\", sensor=\"temp1\"}"
    }
   ]
  },
  {
   "title": "Fan 2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{chip=\"platform_nct6775_2592\", endpoint=\"metrics\", host=\"kvm\", instance=\"kvm.crazyzone.be:9100\", job=\"node-exporter\", sensor=\"fan2\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{chip=\"platform_nct6775_2592\", endpoint=\"metrics\", host=\"kvm\", instance=\"kvm.crazyzone.be:9100\", job=\"node-exporter\", sensor=\"fan2\"}"
    }
   ]
  },
  {
   "title": "Fan 3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{chip=\"platform_nct6775_2592\", endpoint=\"metrics\", host=\"kvm\", instance=\"kvm.crazyzone.be:9100\", job=\"node-exporter\", sensor=\"fan3\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{chip=\"platform_nct6775_2592\", endpoint=\"metrics\", host=\"kvm\", instance=\"kvm.crazyzone.be:9100\", job=\"node-exporter\", sensor=\"fan3\"}"
    }
   ]
  },
  {
   "title": "Fan 4",
   "type": "graph",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{chip=\"platform_nct6775_2592\", endpoint=\"metrics\", host=\"kvm\", instance=\"kvm.crazyzone.be:9100\", job=\"node-exporter\", sensor=\"fan4\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{chip=\"platform_nct6775_2592\", endpoint=\"metrics\", host=\"kvm\", instance=\"kvm.crazyzone.be:9100\", job=\"node-exporter\", sensor=\"fan4\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{chip=\"platform_nct6775_2592\", endpoint=\"metrics\", host=\"kvm\", instance=\"kvm.crazyzone.be:9100\", job=\"node-exporter\", sensor=\"fan1\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{chip=\"platform_nct6775_2592\", endpoint=\"metrics\", host=\"kvm\", instance=\"kvm.crazyzone.be:9100\", job=\"node-exporter\", sensor=\"fan5\"}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_fan_rpm{chip=\"platform_nct6775_2592\", endpoint=\"metrics\", host=\"kvm\", instance=\"kvm.crazyzone.be:9100\", job=\"node-exporter\", sensor=\"fan6\"}"
    }
   ]
  }
 ]
}