{
 "title": "Crazy's Home",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(ALERTS_FOR_STATE,instance)"
    }
   },
   {
    "name": "alertname",
    "query": {
     "query": "label_values(ALERTS_FOR_STATE,alertname)"
    }
   }
  ]
 },
 "panels": [
  { "type": "ryantxu-ajax-panel", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  { "title": "Crazy's Dashboards", "type": "dashlist", "gridPos": { "h": 9, "w": 13, "x": 0, "y": 3 } },
  {
   "title": "CPU  Temp KVM",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"pci0000:00_0000:00:18_3\", endpoint=\"metrics\", host=\"kvm\", instance=\"kvm.crazyzone.be:9100\", job=\"node-exporter\", sensor=\"temp1\"}"
    }
   ]
  },
  {
   "title": "CPU Temp Desktop  Nico",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"pci0000:00_0000:00:18_3\",endpoint=\"metrics\",host=\"nico\",instance=\"nico.crazyzone.be:9100\",job=\"node-exporter\",sensor=\"temp1\"}"
    }
   ]
  },
  {
   "title": "Internet In/Out",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "-irate(ifHCOutOctets{job=\"snmp_gateway.crazyzone.be\", ifName=\"igb0\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "irate(ifHCInOctets{job=\"snmp_gateway.crazyzone.be\", ifName=\"igb0\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "l1_power_usage_value{instance=\"https://power-reader.crazyzone.be/metrics\", job=\"power-reader.crazyzone.be\", unit=\"Watt\"}"
    }
   ]
  },
  {
   "title": "Alerts History",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Firing (-)   /  Pending (+)  " }
   ],
   "targets": [
    {
     "expr": "ALERTS{alertstate=~\"firing\"}",
     "legendFormat": "{{alertname}} {{instance}} {{alertstate}} {{datacenter}}"
    },
    { "expr": "1", "legendFormat": "help_series_x_axes_in_center" }
   ]
  }
 ]
}