apiVersion: v1
kind: PersistentVolume
metadata:
  name: livesqlsb-prometheus-pv-name
  namespace: monitoring
  labels:
    app: livesqlsb-prometheus
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce # required
  nfs:
    server: nas.crazyzone.be
    path: "/volume1/docker-storage/prometheus"