apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-prometheus-kube-prometheus-prometheus-db-prometheus-prometheus-kube-prometheus-prometheus-0
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: livesqlsb-prometheus
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem