apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry-mirror
  name: registry-mirror
spec:
  selector:
    app: registry-mirror
  type: ClusterIP    
  ports:
  - name: registry-mirror
    port: 80
    protocol: TCP
    targetPort: 5000
  