apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'nomadesk-apis'
spec:
  project: 'nomadesk'
  destination:
    name: ''
    namespace: 'nomadesk-apis'
    server: 'https://kubernetes.default.svc'
  source:
    path: 'applications/charts/nomadesk/apis'
    repoURL: '$GIT_URL'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
