apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-power-exporter
spec:
  tls:
    - secretName: {{ .Values.tlssecret }}
      hosts:
      - {{ .Values.hostname }}
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: power-exporter
                port:
                  number: 80
