apiVersion: v1
kind: Service
metadata:
  labels:
    app: power-exporter
  name: power-exporter
spec:
  selector:
    app: power-exporter
  type: ClusterIP    
  ports:
  - name: power-exporter
    port: 80
    protocol: TCP
    targetPort: 80
  