 wekan:
  dbname: wekan
  env:
    - name: "MONGO_URL"
      value: "mongodb://wekan-mongodb:27017"
  endpoint: wekan.crazyzone.be
  root_url: https://wekan.crazyzone.be
  ingress:
    enabled: true
    hosts: [ wekan.crazyzone.be ]
    tls:
      - secretName: crazyzone-be-tls
        hosts:
          - wekan.crazyzone.be
  mongodb:
    persistence:
      existingClaim: "wekan-storage-db-claim"