apiVersion: v1
name: gitea
version: 0.0.1
appVersion: 0.0.1
description: Git server for crazyzone
dependencies:
  - name: rancher
    version: "2.7.1"
    repository: "https://releases.rancher.com/server-charts/latest"
