apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    server: nas.crazyzone.be
    path: "/volume1/docker-storage/loki"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-claim
  namespace: monitoring
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      app: loki
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem