apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins-nmd
  name: jenkins-nmd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-nmd
  template:
    metadata:
      labels:
        app: jenkins-nmd
    spec:
      serviceAccountName: jenkins-nmd
      volumes:
        - name: jenkins-nmd-storage
          nfs: 
            server: nas.crazyzone.be 
            path: /volume1/docker-storage/jenkins-nmd
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
      containers:
      - image: jenkins/jenkins:latest
        name: jenkins-nmd
        volumeMounts:
        - name: jenkins-nmd-storage
          mountPath: /var/jenkins_home   
        - name: dockersock
          mountPath: "/var/run/docker.sock"     
        ports:
        - name: jenkins-nmd
          containerPort: 8080
        - name: jenkins-nmd-jnlp-port
          containerPort: 50000          
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /login
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5          
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
