apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins-nmd
  name: jenkins-nmd
spec:
  selector:
    app: jenkins-nmd
  type: ClusterIP
  ports:
  - name: jenkins-nmd-ui
    port: 8080
    targetPort: 8080
  - name: jenkins-jnlp
    port: 50000
    targetPort: 50000    
