apiVersion: v1
name: minio
version: 1.0.0
appVersion: 1.0.0
description: object storage minio installation
dependencies:
  - name: minio
    version: "5.0.10"
    repository: "https://charts.min.io/"
