minio:
  mode: standalone

  rootUser: "admin"
  rootPassword: "password"

  replicas: 1

  persistence:
    enabled: true
    existingClaim: minio-storage-claim

  ingress:
    enabled: true
    path: /
    hosts:
      - minio.crazyzone.be
    tls: 
      - secretName: secret-tls
        hosts:
          - minio.crazyzone.be
  consoleIngress:
    enabled: true
    path: /
    hosts:
      - minio-console.crazyzone.be
    tls: 
      - secretName: secret-tls
        hosts:
          - minio-console.crazyzone.be

  resources:
    requests:
      memory: 512Mi